### ISSUE TITLE
Minecraft 1.20.4

### ISSUE THREAD

**Issue by Link0Darck** [HelpChat/DeluxeMenus#81]
Good morning,
the plugin does not work in 1.20.4

```
[14:40:29] [Server thread/INFO]: [DeluxeMenus] Enabling DeluxeMenus v1.14.0-Release
[14:40:29] [Server thread/ERROR]: [DeluxeMenus] Could not hook into PlaceholderAPI!
DeluxeMenus will now disable!
[14:40:29] [Server thread/INFO]: [DeluxeMenus] Disabling DeluxeMenus v1.14.0-Release
[14:40:29] [Server thread/ERROR]: Error occurred while disabling DeluxeMenus v1.14.0-Release (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.clear()" because "this.itemHooks" is null
        at com.extendedclip.deluxemenus.DeluxeMenus.onDisable(DeluxeMenus.java:190) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:268) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.extendedclip.deluxemenus.DeluxeMenus.onEnable(DeluxeMenus.java:97) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4061-Spigot-e9ec548-366c3ca]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]    
````

Serveur version : `This server is running CraftBukkit version 4061-Spigot-e9ec548-366c3ca (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)`

**Comment by BlitzOffline** [comment]
Hello @Link0Darck. You are missing PlaceholderAPI from your server. You can download the plugin from here: https://www.spigotmc.org/resources/placeholderapi.6245/

`[14:40:29] [Server thread/ERROR]: [DeluxeMenus] Could not hook into PlaceholderAPI!`

**Comment by Link0Darck** [comment]
> Hello @Link0Darck. You are missing PlaceholderAPI from your server. You can download the plugin from here: https://www.spigotmc.org/resources/placeholderapi.6245/
> 
> `[14:40:29] [Server thread/ERROR]: [DeluxeMenus] Could not hook into PlaceholderAPI!`

Good morning,
there is no way for the plugin to work without another one?

**Comment by BlitzOffline** [comment]
> > Hello @Link0Darck. You are missing PlaceholderAPI from your server. You can download the plugin from here: https://www.spigotmc.org/resources/placeholderapi.6245/
> > `[14:40:29] [Server thread/ERROR]: [DeluxeMenus] Could not hook into PlaceholderAPI!`
> 
> Good morning, there is no way for the plugin to work without another one?

No. DeluxeMenus has a tight coupling with PlaceholderAPI. While it is possible for us to remove the PlaceholderAPI requirement, most features would not work without it as it uses it as a bridge to other plugins.
