### ISSUE TITLE
placeholder action return empty

### ISSUE THREAD

**Issue by FakEEE14** [HelpChat/DeluxeMenus#86]
hi
when you use [placeholder] action and if it's empty it's retrun it's empty

action:

      - '[placeholder] %luckperms_meta_randomstuff%'

error:

[DeluxeMenus] Task #537 for DeluxeMenus v1.14.1-DEV-178 generated an exception
java.lang.NullPointerException: Cannot invoke "com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(String)" because "holder" is null
        at com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:87) ~[DeluxeMenus-1.14.1-DEV-178 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-95]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-95]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-95]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BlitzOffline** [comment]
I am not sure if this is related to the action itself. It seems to me that the error you sent is incomplete. Can you send either full server logs or just check a few lines above the exception sent by you for other exceptions?

**Comment by FakEEE14** [comment]
it's just this error,
i open a menu that have open_commands placeholder
and it's pop this error

**Comment by BlitzOffline** [comment]
Hello @FakEEE14 . It has been a while. Sorry about that. I am wondering if you could share some information with us. What I am looking for is a dump of your menu and your server info. You can get all of this by executing `/dm <menu_name>`.

**Comment by FakEEE14** [comment]
it's just parsing a placeholder when i open a menu with open_commands it's pop this error because the placeholder is empty and it's return null
like 
open_commands:
   - '[placeholder] -%javascript_cooldown_2396_start,players.{player_name}.wardrobe%'

**Comment by iGabyTM** [comment]
Do you still get this error @FakEEE14 ? `ClickActionTask.java:87` is not even the code for the `placeholder` action 🤷🏼

**Comment by FakEEE14** [comment]
i didn't use the newst build right now, i use it and update you with that

**Comment by BlitzOffline** [comment]
Closing this issue because I was not able to recreate. Also, from the stacktrace, another thing seems to be causing the problem. The MenuHandler is null. My best guess at the moment is that something broke before parsing the placeholder, maybe even from a different placeholder and this is just a side effect of that.

If you manage to recreate this issue, please reopen this ticket and put the full server logs with it. Thanks.
